services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webstore
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: webuser
      DB_PASS: webpassword
      DB_NAME: webstore

volumes:
  db_data: